# Generated by Django 4.2.13 on 2026-06-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Entrance', 'Entrance'), ('Bible Procession', 'Bible Procession'), ('Offertory', 'Offertory'), ('Communion', 'Communion'), ('Thanksgiving', 'Thanksgiving'), ('Recessional', 'Recessional'), ('Responsorial Psalm', 'Responsorial Psalm'), ('ord-Kyrie', 'Ordinary — Kyrie'), ('ord-Gloria', 'Ordinary — Gloria'), ('ord-Sanctus', 'Ordinary — Sanctus'), ('ord-Agnus Dei', 'Ordinary — Agnus Dei'), ('ord-Other', 'Ordinary — Other')], max_length=50)),
                ('language', models.CharField(choices=[('Swahili', 'Swahili'), ('Kikuyu', 'Kikuyu'), ('English', 'English'), ('Latin', 'Latin'), ('Other', 'Other')], max_length=50)),
                ('key_signature', models.CharField(blank=True, max_length=20)),
                ('lyrics', models.TextField()),
                ('misa_id', models.CharField(blank=True, max_length=50)),
                ('ord_part', models.CharField(blank=True, max_length=50)),
                ('has_score', models.BooleanField(default=False)),
                ('score_file', models.FileField(blank=True, upload_to='scores/')),
                ('uploaded_by_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
